improve bkup and rstr

diff --git a/adm/bkup b/adm/bkup
--- a/adm/bkup
+++ b/adm/bkup
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #----------------------------------------------------------
-# usage: ./bkup $databox $backup_directory 
+# usage: ./bkup $backup_directory
 #----------------------------------------------------------
 
 WHOAMI=`whoami`
@@ -12,26 +12,28 @@ fi
 
 # global conf load
 SCRIPT_DIR=`dirname $0`
- . ${SCRIPT_DIR}/../global.conf
+. ${SCRIPT_DIR}/../global.conf
+
+# load web/base
+. $ROOT/web/base
 
 # load param
-databox=$1
-bkup_dir=$2
-bkup_dir=`echo $bkup_dir | $SED "s/\/$//g"`
+bkup_dir=$1
 
-if [ ! "$databox" ];then
-  echo "error: please input databox name"
+# disk util check
+disk_usage=`df -k $bkup_dir | grep -v Avail | awk '{print $4}'`
+small_shell_size=`du -sk $ROOT | awk '{print $1}'`
+
+
+if [ $small_shell_size -gt $disk_usage ];then
+  echo -n "error: disk of $bkup_dir is not enough"
   exit 1
 fi
 
-if [ ! -d $ROOT/databox/$databox ];then
-   echo "error: databox{$databox} seems wrong"
-   exit 1
-fi
 
 if [ ! "$bkup_dir" ];then
-  echo "error: please input backdup directory"
-  exit 1
+   echo "error: please input backup direcotry \"./bkup \$backup_directory\""
+   exit 1
 fi
 
 if [ ! -d $bkup_dir ];then
@@ -39,15 +41,24 @@ if [ ! -d $bkup_dir ];then
    exit 1
 fi
 
-# Exec backup
-(cd $ROOT/databox && tar -Jcf $bkup_dir/${databox}.tar.xz ${databox})
+# backup databoxs
+(cd $ROOT/../ && tar -Jcf $bkup_dir/${server}.core.tar.xz small-shell)
 result=$?
-
-if [ $result -eq 0 ];then
-  echo "Backup has been done successfully"
-  echo "please check $bkup_dir"
-else
-  echo "eror: something seems wrong"
-  exit 1
+if [ ! $result -eq 0 ];then
+  echo "warn: something seems wrong for making backup of small-shell core"
 fi
 
+# backuip apps
+target_www=`echo $www | xargs basename -a`
+
+if [ "$cgidir" = "/var/www/cgi-bin" ];then
+  (cd ${www}/../ && tar -Jcf $bkup_dir/${server}.www.tar.xz $target_www)
+else
+  target_cgi=`echo $cgidir | xargs basename -a`
+  (cd ${www}/../ && tar -Jcf $bkup_dir/${server}.www.tar.xz $target_www)
+  (cd ${www}/../ && tar -Jcf $bkup_dir/${server}.cgi.tar.xz $target_cgi)
+fi
+
+echo "backup completed, please check $bkup_dir"
+
+exit 0
diff --git a/adm/rstr b/adm/rstr
--- a/adm/rstr
+++ b/adm/rstr
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #----------------------------------------------------------
-# usage: ./rstr $databox $restore_file
+# usage: ./rstr $backuped_dir
 #----------------------------------------------------------
 
 WHOAMI=`whoami`
@@ -15,45 +15,54 @@ SCRIPT_DIR=`dirname $0`
  . ${SCRIPT_DIR}/../global.conf
 
 # load param
-databox=$1
-rstr_file=$2
+bkuped_dir=$1
 
-if [ ! "$databox" ];then
-  echo "error: please input databox name"
+if [ ! "$bkuped_dir" ];then
+  echo "error: please input backuped directory name"
   exit 1
 fi
 
-if [ ! "$rstr_file" ];then
-  echo "error: please input restore file with full path"
+if [ ! -d ${bkuped_dir} ];then
+  echo "error: it seems there is no backuped directory"
   exit 1
 fi
 
-if [ ! -f $rstr_file ];then
-   echo "error: restore file {$rstr_file} seems wrong"
-   exit 1
-fi
-
-if [ -d $ROOT/databox/${databox} ];then
-  echo "warn: databox{$databox} is still existing"
-  echo "original one will be moved to $ROOT/databox/_${databox}"
-  mv $ROOT/databox/${databox} $ROOT/databox/_${databox}
-fi
-
-# Exec restore
-(cd $ROOT/databox && tar -xf ${rstr_file})
-result=$?
-
-if [ $result -eq 0 ];then
-  chown -R small-shell:small-shell $ROOT/databox/$databox
-  chmod 700 $ROOT/databox/$databox/data
-  chmod 700 $ROOT/databox/$databox/log
-  chmod 700 $ROOT/databox/$databox/hashchain
-  chmod 700 $ROOT/databox/$databox/log.dump
-  chmod 700 $ROOT/databox/$databox/index
-  chown -R small-shell:small-shell $ROOT/databox/${databox}/def
-  chmod 755 $ROOT/databox/${databox}/def/*
-  echo "DATA has been successfully restored"
+# file check
+num_chk=`ls ${bkuped_dir}/*core*xz 2>/dev/null | wc -l`
+if [ $num_chk -gt 1 ];then
+  echo "error: it seems there are more than 2 core file in the directory"
+  exit 1
 else
-  echo "eror: something seems wrong"
-  exit 1
+  rm -rf $ROOT/databox
+  rm -rf $ROOT/users
+  cp ${bkuped_dir}/*core*.xz $ROOT/../
+  (cd $ROOT/../ && tar -xf *core*.xz)
+  chown -R small-shell:small-shell $ROOT
 fi
+
+num_chk=`ls ${bkuped_dir}/*www*xz 2>/dev/null | wc -l`
+if [ $num_chk -gt 1 ];then
+  echo "error: it seems there are more than 2 core file in the directory"
+  exit 1
+else
+  # load web/base
+  . $ROOT/web/base
+  cp ${bkuped_dir}/*www*.xz ${www}/../
+  (cd ${www}/../ && tar -xf *www*.xz)
+fi
+
+num_chk=`ls ${bkuped_dir}/*cgi*xz 2>/dev/null | wc -l`
+if [ $num_chk -gt 1 ];then
+  echo "error: it seems there are more than 2 core file in the directory"
+  exit 1
+elif [ $num_chk -eq 1 ];then
+  cp ${bkuped_dir}/*cgi*.xz ${cgidir}/../
+  (cd ${cgidir}/../ && tar -xf *cgi*.xz)
+fi
+
+echo "-----------------------------------------------------------------------------------------------------"
+echo "backup files are restored, please exec gen just in case and restart Base APP and enable e-cron jobs"
+echo "-----------------------------------------------------------------------------------------------------"
+echo "sudo $ROOT/adm/gen -app #Base APP"
+echo "sudo -u small-shell $ROOT/bin/e-cron ls"
+exit 0
