adapt to debian

diff --git a/adm/gen b/adm/gen
--- a/adm/gen
+++ b/adm/gen
@@ -73,6 +73,12 @@ if [ $line_chk -eq 1 ];then
       exit 1
     fi
 
+    which bc > /dev/null 2>&1
+    if [ ! $? -eq 0 ];then
+      echo "error: please install bc command first"
+      exit 1
+    fi
+
     echo "SHASUM=\"`which sha256sum`\"" >> ${SCRIPT_DIR}/../global.conf
     echo "BASE64_ENC=\"`which base64` -w 0\"" >> ${SCRIPT_DIR}/../global.conf
     echo "BASE64_DEC=\"`which base64` -d\"" >> ${SCRIPT_DIR}/../global.conf
@@ -81,6 +87,7 @@ if [ $line_chk -eq 1 ];then
     echo "FLOCK=\"`which flock`\"" >> ${SCRIPT_DIR}/../global.conf
     echo "PHP=\"`which php`\"" >> ${SCRIPT_DIR}/../global.conf
     echo "CURL=\"`which curl`\"" >> ${SCRIPT_DIR}/../global.conf
+    echo "BC=\"`which bc`\"" >> ${SCRIPT_DIR}/../global.conf
 
     which jq >/dev/null 2>&1
     if [ ! $? -eq 0 ];then
