improve Form dialog of gen command

diff --git a/adm/gen b/adm/gen
--- a/adm/gen
+++ b/adm/gen
@@ -1823,7 +1823,7 @@ if [ "$param" = "-app" ];then
 
     while [ "$ascii_chk_result" = "ERROR" -o "$meta_chk_result" ]
     do
-      echo "error: form name must be ascii text and you can't use meta charactor including space, please try again"
+      echo "error: Form name must be ascii text and you can't use meta charactor including space, please try again"
       echo -n "form_name: "
       read form_name
       ascii_chk_result=`ascii_check $form_name`
@@ -1841,11 +1841,16 @@ if [ "$param" = "-app" ];then
       read databox
     done 
 
-    echo -n "description of the form : "
+    primary_key=`cat $ROOT/databox/$databox/def/col1 | grep name= | $SED "s/name=//g"  | $SED "s/\"//g"`
+    if [ ! "$primary_key" = "hashid" ];then
+      echo "error: primary key must be hashid if you want to use the databox for Form"
+      exit 1
+    fi
+
+    echo -n "description of the Form : "
     read description 
 
-
-    echo -n "Do you want to enable IP whitelisting for this form ? (yes | no): "
+    echo -n "Do you want to enable IP whitelisting for this Form ? (yes | no): "
     read IP_whitelisting
     while [ ! "$IP_whitelisting" = "yes" -a ! "$IP_whitelisting" = "no" ]
     do
@@ -1855,9 +1860,9 @@ if [ "$param" = "-app" ];then
     done
 
     clear
-    datas=`cat $ROOT/databox/$databox/def/col* | grep name=\" | grep -v hashid | $AWK -F "name=" '{print $2}' \
+    datas=`cat $ROOT/databox/$databox/def/col* | grep name=\" | grep -v $primary_key | $AWK -F "name=" '{print $2}' \
     | $SED "s/\"//g" | $SED -z "s/\n/ | /g" | $SED "s/ | $//g"`
-    echo -n "select data that must be included in the form ($datas) : "
+    echo -n "select data that must be included in the Form ($datas) : "
     read key
     
     key_chk=`grep "name=\"$key\"" $ROOT/databox/$databox/def/col*`
@@ -1874,12 +1879,12 @@ if [ "$param" = "-app" ];then
 
 
     if [ "$datas" ];then
-      echo -n "Do you want to add more data to the form (yes | no): "
+      echo -n "Do you want to add more data to the Form (yes | no): "
       read add_form_answer
       while [ ! "$add_form_answer" = "yes" -a ! "$add_form_answer" = "no" ]
       do
         echo "please input yes or no"
-        echo -n "Do you want to add more data to the form ? (yes | no): "
+        echo -n "Do you want to add more data to the Form ? (yes | no): "
         read add_form_answer
       done
     else
@@ -1888,7 +1893,7 @@ if [ "$param" = "-app" ];then
 
     while [ "$add_form_answer" = "yes" -a "$datas" ]
     do 
-      echo -n "additional data that must be included in the form ($datas) : "
+      echo -n "additional data that must be included in the Form ($datas) : "
       read key
       key_chk=`grep "name=\"$key\"" $ROOT/databox/$databox/def/col*`
 
@@ -1904,12 +1909,12 @@ if [ "$param" = "-app" ];then
       datas=`echo $datas | $SED "s/ | $key / /g" | $SED "s/$key | //g" | $SED "s/ | $key//g" | $SED "s/^$key$//g"`
   
       if [ "$datas" ];then
-        echo -n "Do you want to add more data to the form ? (yes | no): "
+        echo -n "Do you want to add more data to the Form ? (yes | no): "
         read add_form_answer
         while [ ! "$add_form_answer" = "yes" -a ! "$add_form_answer" = "no" ]
         do
           echo "please input yes or no"
-          echo -n "Do you want to add more data to the form ? (yes | no): "
+          echo -n "Do you want to add more data to the Form ? (yes | no): "
           read add_form_answer
         done
       fi
@@ -1918,7 +1923,7 @@ if [ "$param" = "-app" ];then
     # load base info
     . $ROOT/web/base
     clear
-    echo "form will be generated by following order, please check it"
+    echo "Form will be generated by following order, please check it"
     echo "-----------------------------------------------------------------"
     echo ""
     echo "APP type: $apptype"
@@ -2069,7 +2074,7 @@ if [ "$param" = "-app" ];then
 
     while [ "$ascii_chk_result" = "ERROR" -o "$meta_chk_result" ]
     do
-      echo "error: form name must be ascii text and you can't use meta charactor including space, please try again"
+      echo "error: APP name must be ascii text and you can't use meta charactor including space, please try again"
       echo -n "app_name: "
       read app
 
