add get.attr option to ops command

diff --git a/adm/ops b/adm/ops
--- a/adm/ops
+++ b/adm/ops
@@ -82,6 +82,11 @@ do
 
   fi
 
+  if [[ $param == get.attr* ]]; then
+    action=`echo $param | $AWK -F":" '{print $1}'`
+    user_name=`echo $param |  $AWK -F":" '{print $2}' | $AWK -F"{" '{print $1}'`
+  fi
+
   if [[ $param == initialize.usr:* ]]; then
     action=`echo $param | $AWK -F":" '{print $1}'`
     user_name=`echo $param |  $AWK -F":" '{print $2}' | $AWK -F"{" '{print $1}'`
@@ -337,6 +342,21 @@ if [[ $action == set.attr* ]];then
     echo "error: failed to set attribute"
   fi
 
+fi
+
+if [[ $action == get.attr* ]];then
+  user_id=`echo "$user_name" | $SHASUM | $AWK '{print $1}'`
+  if [ "$app" ];then
+    user_dir="$ROOT/users/${app}.${user_id}"
+  else
+    user_dir="$ROOT/users/${user_id}"
+  fi
+
+  if [ ! -d $user_dir ];then
+    echo "error: there is no user ($user_name)"
+    exit 1
+  fi
+  cat $user_dir/attr
 fi
 
 # Handle table tagging request
