change WEB APP controller name, sbin/que name and improve indent of HTML of WEB APP

diff --git a/web/src/cgi-bin/tmplt_controller_form b/web/src/cgi-bin/tmplt_controller_form
--- a/web/src/cgi-bin/tmplt_controller_form
+++ b/web/src/cgi-bin/tmplt_controller_form
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+###############################
+# controller for FORM
+###############################
+IP_whitelisting=%%IP_whitelisting
+
 echo "Content-Type: text/html"
 echo ""
 
@@ -8,8 +13,6 @@ echo ""
 
 # load remote addr
 remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`
-
-IP_whitelisting=%%IP_whitelisting
 
 # IP restriction check
 if [ "$IP_whitelisting" = "yes" ];then
@@ -31,18 +34,9 @@ if [ "$IP_whitelisting" = "yes" ];then
   fi
 fi
 
-# auth for small-shell databox
-authkey="%%authkey"
-auth_req=`${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:%%app user_agent:%%app`
-user_name=`echo $auth_req | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}'`
-session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
-pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`
-
-
 param=`date +%s`
 param="$param:$RANDOM"
 count=1
-
 while [ -f %%www/tmp/${param} ]
 do
  sleep 0.01
@@ -53,7 +47,6 @@ do
  fi
 done
 
-
 # parse QUERY_STRING
 echo $QUERY_STRING | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > %%www/tmp/${param}
 cat %%www/tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" > %%www/tmp/${param}.load
@@ -62,6 +55,18 @@ chmod 755 %%www/tmp/${param}.load
 # load query string
 .  %%www/tmp/${param}.load
 rm  %%www/tmp/${param}*
+
+# auth for small-shell databox
+authkey="%%authkey"
+auth_req=`${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:%%app user_agent:%%app`
+user_name=`echo $auth_req | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}'`
+session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
+pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`
+
+if [ ! "$session" -o ! "$pin" ];then
+  echo "error: internal key authentication failure"
+  exit 1
+fi
 
 # dump POST data
 if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then
diff --git a/web/src/cgi-bin/tmplt_controller_noauth b/web/src/cgi-bin/tmplt_controller_noauth
--- a/web/src/cgi-bin/tmplt_controller_noauth
+++ b/web/src/cgi-bin/tmplt_controller_noauth
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+##########################################
+# controller for Scratch APP #none auth
+##########################################
+
 authkey="%%authkey"
 IP_whitelisting=%%IP_whitelisting
 IP_persistence="yes"
@@ -15,12 +19,6 @@ fi
 if [ "$User_agent_persistence" = "yes" ];then
   user_agent=`echo $HTTP_USER_AGENT | $SED "s/:/-/g" | $SED "s/ /_/g"`
 fi
-
-# auth for small-shell databox
-auth_req=`${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:%%app user_agent:${user_agent}`
-user_name="guest"
-session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
-pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`
 
 # load remote addr
 remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`
@@ -83,6 +81,19 @@ if [[ ! "$req" == *stats && ! "$req" == *file ]];then
   echo ""
 fi
 
+# auth for small-shell databox
+auth_req=`${small_shell_path}/bin/extension_auth key_auth:${authkey} remote_addr:${remote_addr} app:%%app user_agent:${user_agent}`
+user_name="guest"
+session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
+pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`
+
+if [ ! "$session" -o ! "$pin" ];then
+  echo "Content-Type: text/html"
+  echo ""
+  echo "error: internal key authentication failure"
+  exit 1
+fi
+
 # dump POST data
 if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then
 
@@ -102,6 +113,7 @@ if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then
   %%www/bin/parse.sh $session $method
 
 fi
+
 
 #----------------------------
 # routing to action scripts
@@ -128,11 +140,7 @@ case "$req" in
   "file")
     %%www/bin/%%app_dl.sh session:$session pin:$pin user_name:$user_name id:$id ;;
 
-
-   #--------------------------------
-   # sub app routing section
-   #--------------------------------
-
+  # sub app routing section
 
   *)
     echo "error: wrong request";;
